// Стабильные id реестров — без импорта контента, чтобы FactKey не зацикливал arcs/ACH (#258).
export type AchId =
  'first'
  | 'brat'
  | 'night'
  | 'moo10'
  | 'fifty5'
  | 'fence'
  | 'legend'
  | 'rude'
  | 'saint'
  | 'floor'
  | 'year'
  | 'cow'
  | 'ram'
  | 'promises20'
  | 'amnesty'
  | 'shaved'
  | 'meet'
  | 'cafe'
  | 'hash'
  | 'card'
  | 'barter'
  | 'customer'
  | 'nephew'
  | 'lend'
  | 'lend50'
  | 'redo'
  | 'toast'
  | 'newjob'
  | 'wife'
  | 'choice'
  | 'sorry'
  | 'arc_boris'
  | 'arc_beton'
  | 'arc_rubik'
  | 'arc_razmik'
  | 'arc_samvel'
  | 'arc_niva'
  | 'arc_nune'
  | 'arc_grant'
  | 'group'
  | 'wrong'
  | 'tier1'
  | 'tier2'
  | 'tier3'
  | 'idle'
  | 'deleted'
  | 'edited'
  | 'typo'
  | 'sticker'
  | 'fwd'
  | 'react'
  | 'dead'
  | 'away'
  | 'nightowl'
  | 'forgive'
  | 'invoice'
  | 'loan'
  | 'heir'
  | 'threat'
  | 'arc_death'
  | 'arc_garik'
  | 'arc_tile'
  | 'arc_grandpa'
  | 'memory'
  | 'liar'
  | 'liar3'
  | 'blocked'
  | 'tribunal'
  | 'vendetta'
  | 'cowpeace'
  | 'countersuit'
  | 'blood_brother'
  | 'habit'
  | 'q_hash'
  | 'q_niva'
  | 'q_tamada'
  | 'q_lottery'
  | 'q_parking'
  | 'q_mama'
  | 'q_crypto'
  | 'q_photo'
  | 'q_witness'
  | 'q_goat'
  | 'payday'
  | 'court'
  | 'strasbourg'

export type CastId =
  'boris'
  | 'grant'
  | 'nune'
  | 'samvel'
  | 'karine'
  | 'garik'
  | 'arsen'
  | 'mkrtich'
  | 'niva'
  | 'mama'
  | 'intercom'
  | 'judge'
  | 'goar'
  | 'razmik'
  | 'rubik'

export type ArcId =
  'boris'
  | 'beton'
  | 'samvel'
  | 'niva'
  | 'nune'
  | 'grant'
  | 'rubik'
  | 'razmik'
  | 'alik_death'
  | 'garik'
  | 'tile'
  | 'grandpa'

export type TopicId =
  'beton'
  | 'niva'
  | 'wedding'
  | 'bank'
  | 'ram'
  | 'food'
  | 'relative'
  | 'customs'
  | 'history'
  | 'cosmic'

export type ClaimKey =
  'money_jar'
  | 'money_dubai'
  | 'money_noah'
  | 'money_wife'
  | 'money_apricots'
  | 'money_deposit'
  | 'money_wall'
  | 'money_mattress'
  | 'money_crypto'
  | 'money_garni'
  | 'money_ferry'
  | 'money_safe'
  | 'money_foundation'
  | 'money_niva'
  | 'sent'
  | 'no_money'
  | 'grandpa_dead'
  | 'grandpa_alive'
  | 'customer_owes'
  | 'customer_paid'
  | 'beton'
  | 'crane_wedding'
  | 'eagle'

export const EXTRAS = ['baran', 'grachik', 'gagik', 'tamada'] as const
export type ExtraId = (typeof EXTRAS)[number]
export type WhoId = CastId | ExtraId
