// Правила, которые статистический бот покрытия не достигает, но у которых есть доказательство
// вне симуляции: прямой случай в proven.test.ts. Имя → содержательная причина (#230): не шаблон
// от имени. Общая константа на всех — мёртвая метаданная (#130). Новое правило сюда — только
// с случаем в proven.test.ts, который краснеет, если правило сломать.

export const PROVEN: Record<string, string> = {
  Quiet_Dead_AlikAway: 'Quiet_Dead_AlikAway: пачка молчит при alik_dead',
  Quiet_Dead_PeriodLine: 'Quiet_Dead_PeriodLine: смена суток молчит при alik_dead',
  Quiet_Dead_PromiseDue: 'Quiet_Dead_PromiseDue: срок обещания молчит при alik_dead',
  Quiet_Blocked_AlikAway: 'Quiet_Blocked_AlikAway: пачка молчит при blocked',
  Quiet_Blocked_PeriodLine: 'Quiet_Blocked_PeriodLine: смена суток молчит при blocked',
  Quiet_Blocked_PromiseDue: 'Quiet_Blocked_PromiseDue: срок обещания молчит при blocked',
  Quiet_PhoneKarine_AlikIdle: 'Quiet_PhoneKarine_AlikIdle: простой молчит, телефон у Карине',
  Quiet_PhoneKarine_AlikAway: 'Quiet_PhoneKarine_AlikAway: пачка молчит, телефон у Карине',
  Quiet_PhoneKarine_StoryBeat: 'Quiet_PhoneKarine_StoryBeat: сюжет молчит, телефон у Карине',
  Quiet_PhoneKarine_PeriodLine: 'Quiet_PhoneKarine_PeriodLine: сутки молчат, телефон у Карине',
  Quiet_PhoneKarine_PromiseDue: 'Quiet_PhoneKarine_PromiseDue: срок молчит, телефон у Карине',
  Phone_Karine_AlikTurn: 'Phone_Karine_AlikTurn: ход — ответ Карине, не Алика',
  Phone_Karine_PlayerMessage: 'Phone_Karine_PlayerMessage: тон — ответ Карине',
  Phone_Karine_PlayerSays: 'Phone_Karine_PlayerSays: кнопка — ответ Карине',
  Turn_Blocked: 'Turn_Blocked: ход при blocked — ALT/отмазка',
  Turn_Vendetta: 'Turn_Vendetta: ход в режиме вендетты',
  Rude_Vendetta: 'Rude_Vendetta: грубость в режиме вендетты',
  // бот покрытия свободным текстом «спасибо»/«привет» не пишет (FREE в bot.ts)
  Tone_Thanks: 'Tone_Thanks: бот не пишет «спасибо» свободным текстом',
  Tone_Greeting: 'Tone_Greeting: бот не пишет «привет» свободным текстом',
  Says_sorry_blocked: 'Says_sorry_blocked: извинение при blocked',
  Says_sorry_blocked_hinted: 'Says_sorry_blocked_hinted: извинение после подсказки блока',
  Says_via_mama: 'Says_via_mama: «через маму» без блока',
  Finale_boris_brigadir: 'Finale_boris_brigadir: финал Бориса — бригадир',
  Finale_boris_toyou: 'Finale_boris_toyou: финал Бориса — тебе',
  Finale_samvel_groom: 'Finale_samvel_groom: финал Самвела — жених',
  Finale_niva_chose: 'Finale_niva_chose: финал Нивы — выбрал',
  Finale_niva_chose_or: 'Finale_niva_chose_or: финал Нивы — или',
  Finale_rubik_karine: 'Finale_rubik_karine: финал Рубика/Карине',
  Finale_alik_death_sulk: 'Finale_alik_death_sulk: финал смерти — обида',
  Finale_grandpa_revoke: 'Finale_grandpa_revoke: финал деда — отзыв',
  Finale_razmik_swap: 'Finale_razmik_swap: финал Размика — обмен',
  Finale_razmik_union: 'Finale_razmik_union: финал Размика — союз',
  Ending_family: 'Ending_family: концовка семьи',
  Ending_ram: 'Ending_ram: концовка барана',
  Ending_honest: 'Ending_honest: честная концовка',
  Ending_vendetta: 'Ending_vendetta: концовка вендетты',
  Ending_payday_real: 'Ending_payday_real: концовка выплаты — real',
  Ending_payday_niva: 'Ending_payday_niva: концовка выплаты — niva',
  Ending_payday_notyou: 'Ending_payday_notyou: концовка выплаты — notyou',
  Ending_payday_lavash: 'Ending_payday_lavash: концовка выплаты — lavash',
  Ending_payday_strasbourg: 'Ending_payday_strasbourg: концовка выплаты — strasbourg',
  Payday_real: 'Payday_real: исход выплаты real',
  Payday_niva: 'Payday_niva: исход выплаты niva',
  Payday_notyou: 'Payday_notyou: исход выплаты notyou',
  Payday_lavash: 'Payday_lavash: исход выплаты lavash',
  Payday_strasbourg: 'Payday_strasbourg: исход выплаты strasbourg',
  // бот закрывает экран концовки сразу (#190) — AlikTurn в эндгейме всё ещё не видит
  Endgame_Turn: 'Endgame_Turn: ход в эндгейме',
  // пока экран концовки открыт, бот его сразу закрывает — эти события не успевают (#190)
  Quiet_PaydayOpen_AlikAway: 'Quiet_PaydayOpen_AlikAway: пачка за экраном концовки выплаты',
  Quiet_PaydayOpen_PeriodLine: 'Quiet_PaydayOpen_PeriodLine: сутки за экраном концовки выплаты',
  Quiet_PaydayOpen_StoryBeat: 'Quiet_PaydayOpen_StoryBeat: сюжет за экраном концовки выплаты',
  // финалы после выплаты — там тишина (#136)
  Finale_beton_ledger: 'Finale_beton_ledger: финал бетона — ведомость',
  Finale_nune_ledger: 'Finale_nune_ledger: финал Нуне — ведомость',
  Away_ColdWar: 'Away_ColdWar: колкость в пачке при обиде без пропажи',
  Quiet_Offended_AlikAway: 'Quiet_Offended_AlikAway: тишина обиженного в пачке',
  // бот копит ≤3 просрочек; амнистия — сцена на куче (#149)
  Scene_amnesty: 'Scene_amnesty: сцена амнистии при куче просрочек',
  // ставка «усы» — прямой случай; бот редко копит срок со stake (#285)
  Due_StakeShave: 'Due_StakeShave: сорванный срок со ставкой усов',
  Due_StakeKept: 'Due_StakeKept: сдержал слово при ставке усов',
}
